import { type NextPage } from "next";
import Head from "next/head";
import { Todos } from "~/component/Todos";
import { CreateTodo } from "~/component/CreateTodo";
import { signIn, useSession } from "next-auth/react";
import NavBar from "~/component/NavBar";
import Footer from "~/component/Footer";
import Script from "next/script";


const Home: NextPage = () => {
  const { data: sessionData } = useSession();

  return (
    <>
      <Head>
        <title>T3 ToDo App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
        {/* Google Analytics */}
        <Script
        src="https://www.googletagmanager.com/gtag/js?id=G-GWMPJW8TT8"
        strategy="afterInteractive"
      />
      <Script id="google-analytics" strategy="afterInteractive">
        {`
          window.dataLayer = window.dataLayer || [];
          function gtag(){dataLayer.push(arguments);}
          gtag('js', new Date());
          gtag('config', 'G-GWMPJW8TT8');
        `}
      </Script>
      <main className="flex min-h-screen flex-col justify-between bg-gradient-to-b from-[#2e026d] to-[#15162c]">
        <NavBar />
        <div className="w-full text-center flex-grow flex items-center justify-center">
          {sessionData ? (
            <div className="flex 2xl:w-1/3 xl:w-1/2 lg:w-1/2 md:w-4/5 w-full mx-3 flex-col gap-4 rounded-xl bg-white/10 p-4 text-white">
              <p className="text-xl font-bold underline text-center">ToDo List</p>
              <Todos />
              <CreateTodo />
            </div>
        ) : <div className="flex-col text-white text-zinc-400xl pb-24">
              <div className="text-5xl font-extrabold m-2">Welcome to the new Todo List App!</div>
              <div className="text-3xl font-extrabold text-gray-500">Developed with the T3 stack (Next.js, Prisma, and tRPC).</div>
              <button className="w-full rounded-lg bg-blue-700 px-5 py-2.5 text-center text-sm font-medium 
                      text-white hover:bg-blue-800 focus:outline-none focus:ring-4 
                      focus:ring-blue-300 dark:bg-blue-600 dark:hover:bg-blue-700 
                      dark:focus:ring-blue-800 sm:w-auto mt-10"
                      onClick={() => void signIn()}
              >Sign in</button>
            </div>
        }
        </div>
        <Footer />
      </main>
    </>
  );
};

export default Home;

